#!/bin/bash

deploy()
{
	for file in $1/*; do
		if [ -f $file ]; then
			rm -rf ~/.`basename $file`
			ln $file ~/.`basename $file`
		fi
	done

}

shell="${1:-bash}"

mkdir -p ~/bin
rm -f ~/bin/dots
ln dots ~/bin/dots
mkdir -p ~/bin
rm -rf ~/bin/git
ln -s `realpath .`/dirs/git_scripts ~/bin/git

rm -rf ~/.git_template
ln -s `realpath .`/dirs/git_template ~/.git_template

for f in bin/*; do
	rm -f ~/$f
	ln $f ~/$f
done


deploy universal
deploy $shell
