#!/bin/bash

shell="${1:-bash}"

rm -f ~/bin/dots
ln dots ~/bin/dots

for file in $shell/*; do
	rm -f ~/.`basename $file`
	ln $file ~/.`basename $file`
done

for file in universal/*; do
	rm -f ~/.`basename $file`
	ln $file ~/.`basename $file`
done
