#!/usr/bin/env python3

from glob import glob
import sys
import itertools
import os

verbose = False
if len(sys.argv) > 1 and (sys.argv[1] == "--verbose" or sys.argv[1] == "-v"):
    verbose = True

IGNORE_FILE = ".ignore"
HOME = os.environ["HOME"]
HERE = os.getcwd()

ignores = [ (".ignore", ".git") ]
if os.access(IGNORE_FILE, os.R_OK):
    with open(".ignore", "r") as f:
        ignores += [ glob(line.strip()) for line in f ]
    ignores = set(itertools.chain.from_iterable(ignores))

files = [ f for f in os.listdir('.') if f not in ignores ]

for f in files:
    myfile = os.path.join(HERE, f)
    link = os.path.join(HOME, f)
    try:
        os.remove(link)
    except FileNotFoundError:
        pass
    os.symlink(myfile, link)
    if verbose:
        print(f"{link} -> {myfile}")

