#!/bin/bash

base=$HOME/git/Dotfiles

if [ $# -ne 1 ]; then
	echo "Usage: dots save|deploy"
fi

cd $base
if [ "$1" -eq "save" ] || [ "$1" -eq "push" ] || [ "$1" -eq "commit" ]; then
	git add .
	git commit -m "`git changed`"
	git push
elif [ "$1" -eq "deploy" ] || [ "$1" -eq "pull" ]; then
	git pull
fi

