#!/bin/bash

set -e

mkdir $HOME/bin
mkdir $HOME/git
mkdir $HOME/.ssh
mkdir $HOME/documents

sudo apt-get install vim
sudo apt-get install git
sudo apt-get install curl

cd $HOME/.ssh
ssh-keygen
cat id_rsa.pub

tput bold
echo "add this to your github"
tput sgr0

r

git clone git@github.com:chrisdean258/school.git

cd $HOME/git

git clone git@github.com:chrisdean258/vimrc.git
git clone git@github.com:chrisdean258/Dotfiles.git


$HOME/git/Dotfiles/dots deploy

cd $HOME/.ssh

vim config

cat id_rsa.pub | ssh hydra "cat >> ~/.ssh/authorized_keys"
