#!/bin/bash

mkdir $HOME/bin
mkdir $HOME/git
mkdir $HOME/.ssh

ssh-keygen
cat ~/.ssh/id_rsa.pub

tput bold
echo "add this to your github or bitbucket"
tput sgr0

cd ~/git
git clone git@github.com:chrisdean258/vimrc.git
git clone git@github.com:chrisdean258/Dotfiles.git

$HOME/git/Dotfiles/dots deploy

