#!/bin/bash
-()
{
	builtin cd -
}

alias cd="cdls"

cdls()
{
	builtin cd "$@" &&
		ls &&
		echo `realpath .` >> ~/.jmp/to.txt && 
		sed -i 1d ~/.jmp/to.txt
}

md()
{
	mkdir "$@" && cd "$@"
}

j()
{
	jmps="$HOME/.jmp"
	if [ $# -ne 0 ]
	then
		pattern=".*$(echo "$@" | sed "s/\s\+/.*\/.*/g")[^\/]*$"
	fi

	if echo $PWD | grep -qi "$pattern"
	then
		new_dir=$(
		tac $jmps |
		grep -i "$pattern" |
		awk '{ if (!a[$0]++) print $0 }' |
		awk '{ print $0; if(!a) a = $0 }; END { print a }' |
		grep -m 1 -A 1 "^$PWD$" |
		\tail -1
		)
	else
		new_dir=$(
		tac $jmps |
		grep -i "$pattern" |
		awk '{ if (!a[$0]++) print $0 }' |
		\head -n 1
		)

	fi

	if ! [ -z "$new_dir" ]
	then 
		if [ -d "$new_dir" ]
		then
			builtin cd $new_dir 
		else
			temp=$(mktemp)
			mv $jmps $temp
			grep -v "^$new_dir$" $temp > $jmps
			rm $temp
			j "$@"
		fi
	fi
}

jsetup()
{
	time=$(date +%D --date="-2 month")
	find $HOME -type d -not -path "*/\.*" -newermt $time > $HOME/.jmp
}


vi()
{
	if [ $# -ne 0 ]
	then
		pattern=".*$(echo "$@" | sed "s/\s\+/.*\/.*/g")[^\/]*$"
	fi

	file=""
	file=$(find $dir | grep "$pattern" | xargs file | grep -i "text" | cut -d ":" -f 1 | awk '{ a=$0; print gsub(/\//,""), a }' | sort -n -s | cut -d" " -f2- | \head -n 1)
	[ -z "$file" ] && \
		file=$(find $dir | grep -i "$pattern" | xargs file | grep -i "text" | cut -d ":" -f 1 | awk '{ a=$0; print gsub(/\//,""), a }' | sort -n -s | cut -d" " -f2- | \head -n 1)

	if [ -f "$file" ]; then
		/usr/bin/vim $file
	fi
}
