#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --show-toplevel`"
trap 'rm -f "$dir/$$.tags"' EXIT
ctags -R --tag-relative -f"$dir/$$.tags" --languages=-javascript,sql
mv "$dir/$$.tags" "$dir/.tags"
