#!/bin/bash


if [ $# -eq 0 ]; then
	git branch
elif [ $# -eq 1 ] && [ `git branch | grep $1` ]; then
	git co "$@"
elif echo "$1" | grep "^-"; then
	git branch "$@"
else
	git co -b "$@"
	git branch --set-upstream-to origin/"$@"
fi

