#!/bin/bash

set -e

if [ $# -lt 1 ]; then
	echo "Usage: git delete-repo repo_name" 1>&2
	exit 2
fi

REPO="$1"
USER=$(git config user.username) || true
if [ -z "$USER" ]; then
	USER=$(git config user.email | sed "s/@.*//")
fi

read -s -p "Password: " PASSWORD
echo

curl -u "$USER:$PASSWORD" -X "DELETE" "https://api.github.com/repos/$USER/$REPO"
