#!/bin/bash

set -e

if [ $# -lt 1 ]; then
	echo "Usage: git new-repo repo_name" 1>&2
	exit 2
fi

REPO="$1"
USER=$(git config user.username) || true
if [ -z "$USER" ]; then
	USER=$(git config user.email | sed "s/@.*//")
fi

read -s -p "Password: " PASSWORD
echo

mkdir -p "$REPO"
cd "$REPO"

git init

curl -u "$USER:$PASSWORD" "https://api.github.com/user/repos" -d "{\"name\":\"$REPO\"}"
git remote add origin "git@github.com:$USER/$REPO.git"

echo "# $REPO" > README.md
touch .gitigore

git add -A .
git commit -m "Initial Commit"
git push origin master
