#!/bin/bash

cur_branch=$(git branch | grep "^\*" | sed "s/^\* //")


for branch in $(git branch | sed "s/[ \s\*]//g" | grep -v "master"); do
	git co "$branch"
	git pull
	git rebase master
	git push
done


git co "$cur_branch"
