#!/bin/bash

cur_branch=$(git branch | grep "^\*" | sed "s/^\* //")


for branch in $(git branch --format='%(refname:short)' | grep -v "master"); do
	git co "$branch"
	git pull --rebase
	git rebase master
	git pull --rebase
	git push
done


git co "$cur_branch"
