#!/bin/bash

if svn info >/dev/null 2>&1; then
	snv commit -m "$*"
	exit $?
fi

comment="$*"

if [ "$*" = "..." ]; then
	comment="$(git log -1 --pretty=%B)"
	echo -n "\"$comment\"? "
	read -r resp
	[ -n "$resp" ] && comment="$resp"
fi

! test -n "$(git remote)" || git pull --autostash
if [ -z "$comment" ]; then
	git commit -a
else
	git commit -am "$comment"
fi
! test -n "$(git remote)" || git push

