#!/bin/bash

mic="alsa_input.usb-Solid_State_System_Co._Ltd._LCS_USB_Audio_000000000000-00.analog-mono"
headphones="alsa_output.usb-Generic_Turtle_Beach_P11_Headset_0000000001-00.analog-stereo"

chrome_output="$(pactl list sink-inputs | sed "/[Cc]hromium|[Ch]rome/q" | grep "^Sink Input #" | head -n 1 | sed "s/^Sink Input #//")"
chrome_sink=$(pactl load-module module-null-sink sink_name=chrome sink_properties=device.description=Chrome-ouput)
pactl move-sink-input $chrome_output chrome
pactl load-module module-loopback sink=$headphones source=chrome.monitor

pactl load-module module-null-sink sink_name=audacity_input sink_properties=device.description=Audacity-inpu
pactl load-module module-loopback sink=audacity_input source=chrome.monitor
pactl load-module module-loopback sink=audacity_input source=$mic



