#!/bin/sh
echo MPOWH5: bluez_sink.C4_6E_7B_D0_A5_D5.a2dp_sink
echo MPOWH5.monitor: bluez_sink.C4_6E_7B_D0_A5_D5.a2dp_sink.monitor
echo tutlebeach:  alsa_output.usb-Generic_Turtle_Beach_P11_Headset_0000000001-00.analog-stereo
echo turtlebeach.monitor:  alsa_output.usb-Generic_Turtle_Beach_P11_Headset_0000000001-00.analog-stereo.monitor
echo speakers: alsa_output.pci-0000_00_1f.3.analog-stereo
echo speaker.smonitor: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
echo microphone: alsa_input.pci-0000_00_1f.3.analog-stereo
echo tutlebeachmic: alsa_input.usb-Generic_Turtle_Beach_P11_Headset_0000000001-00.iec958-stereo
echo externalmic: alsa_input.usb-Solid_State_System_Co._Ltd._LCS_USB_Audio_000000000000-00.analog-mono
echo MPOWH3: bluez_sink.FC_58_FA_70_46_E1.headset_head_unit
echo MPOWH3.monitor: bluez_sink.FC_58_FA_70_46_E1.headset_head_unit.monitor
