#!/bin/sh


if [ $# -eq 0 ]; then
	exec pavucontrol
fi

sinks="$(pactl list sinks | grep -E "Sink #|device.description = " | sed '$!N;s/\n/ /' | sed "s/Sink #\([0-9]*\).*\"\(.*\)\"/\1 \2/g" | sed "s/Built-in Audio Analog Stereo$/Speakers/g")"
sources="$(pactl list sink-inputs | grep -E "Sink Input #|application.name = " |  sed '$!N;s/\n/ /' | sed "s/Sink Input #\([0-9]*\).*\"\(.*\)\"/\1 \2/g")"

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
	echo "Usage: audio [list [sources|sinks] | [source] sink | restart]" 1>&2
	exit 1
elif [ "$1" = "list" ]; then
	if [ $# -eq 1 ]; then
		echo "Sinks:"
		echo "$sinks"
		echo "Sources:"
		echo "$sources"
	elif [ $2 = "sinks" ];then
		echo "$sinks" | grep .
	elif [ $2 = "sources" ];then
		echo "$sources" | grep .
	fi
	exit 0
elif [ "$1" = "restart" ]; then
	exec pulseaudio -k
fi

if [ $# -eq 1 ]; then
	src=$(echo "$sources" | awk '{print $1}')
	sink=$(echo "$sinks"  | awk "index(\$0, $1) {print \$1; exit(0)}")
else
	src=$(echo "$sources" | awk "index(\$0, $1) {print \$1}")
	sink=$(echo "$sinks"  | awk "index(\$0, $2) {print \$1; exit(0)}")
fi

for i in $src; do 
	echo pactl move-sink-input $i $sink
	pactl move-sink-input $i $sink
done

