#!/bin/sh

xbright()
{
	brightness=$(xrandr --verbose | awk '/Brightness/ { print $2 }')

	if [ $# -eq 0 ]; then 
		echo "$brightness" | awk '{ print int($1 * 100) }'
		exit
	fi

	new_bright="$(echo "$1" | awk '{ print $1 / 100.0 }')"
	if echo "$1" | grep -q "^[+-]"; then
		new_bright=$(echo "$brightness" "$new_bright" | awk '{ print $1 + $2 }')
	fi


	new_bright=$(echo "$new_bright" | awk '$1 <= 1.2 && $1 > 0')
	output="$(xrandr | awk '/ connected/ {print $1}' |  head -n 1)"

	echo xrandr --output "$output" --brightness "${new_bright:-$brightness}"
	xrandr --output "$output" --brightness "${new_bright:-$brightness}"
}


sbright()
{
	raw=$(cat /sys/class/backlight/*/brightness)
	max=$(cat /sys/class/backlight/*/max_brightness)
	brightness=$(echo $raw $max | awk '{ print 1.0 * $1 / $2 }')

	if [ $# -eq 0 ]; then 
		echo "$brightness" | awk '{ print int($1 * 100) }'
		exit
	fi

	new_bright="$(echo "$1" | awk '{ print $1 / 100.0 }')"
	if echo "$1" | grep -q "^[+-]"; then
		new_bright=$(echo "$brightness" "$new_bright" | awk '{ print $1 + $2 }')
	fi

	new_bright=$(echo "$new_bright" "$max" | awk '{print int($1 * $2)}')
	if [ $new_bright -le $max ] && [ $new_bright -ge 0 ]; then
		echo $new_bright | sudo tee /sys/class/backlight/*/brightness
	fi
}

sbright "$@" || xbright "$@"
