#!/bin/sh

MAC_of()
{
	choices=$(bt-device -l | sed "1d" | grep -Eie "$*")
	[ "$(echo "$choices" | wc -l)" -eq 1 ] && cmd="cat" || cmd="dmenu -i"
	echo "$choices" | $cmd | sed "s/.*(\(.*\)).*/\1/"
}

if [ "$1" = "-d" ]; then
	shift
	mac="$(MAC_of "$*")"
	echo "disconnect $mac" | bluetoothctl
elif [ $# -gt 0 ]; then
	mac="$(MAC_of "$*")"
	[ -z "$mac" ] && exit 1
	echo "connect $mac" | bluetoothctl
else
	blueman-manager >/dev/null 2>&1 &
fi



