#!/bin/sh

if [ $# -gt 0 ]; then
	choices=$(bt-device -l | sed "1d" | grep -Ee "$*")
	[ "$(echo "$choices" | wc -l)" -eq 1 ] && cmd="cat" || cmd="dmenu -i"
	mac=$(echo "$choices" | $cmd | sed "s/.*(\(.*\)).*/\1/")
	[ -z "$mac" ] && exit 1
	echo "connect $mac" | bluetoothctl
else
	blueman-manager >/dev/null 2>&1 &
fi



