#!/bin/sh

MAC_of()
{
	choices=$(bt-device -l | sed "1d" | grep -Eie "$*")
	[ "$(echo "$choices" | wc -l)" -eq 1 ] && cmd="cat" || cmd="dmenu -i"
	echo "$choices" | $cmd | sed "s/.*(\(.*\)).*/\1/"
}

if [ $# -eq 0 ]; then
	exec blueman-manager 2>&1 >/dev/null &
fi
while [ $# -gt 0 ]; do
	case $1 in
		-d) echo "disconnect" | bluetoothctl ;;
		--d) echo "disconnect" | bluetoothctl ;;
		-p) pushbullet "BTDC" "BTDC";;
		*)
			mac="$(MAC_of "$*")"
			[ -z "$mac" ] && exit 1
			echo "connect $mac" | bluetoothctl
			;;
	esac
	shift
done
