#!/bin/sh

if [ $# -eq 0 ] || ! [ -t 1 ]; then 
	exec cat "$@"
fi

for f in "$@"; do
	if [ -d "$f" ]; then 
		ls --color=auto --group-directories-first "$f"
	elif ! [ -f "$f" ]; then
		echo "ccat: $f: no such file or directory" >&2
	elif echo "$f" | grep -q "\.txt$" || [ "$(wc -l < "$f")" -gt 500 ] || [ "$(wc -c < "$f")" -gt 5000 ] ; then
		cat "$f"
	else
		vimcat "$f"
	fi
done
