#!/bin/sh

case "$1" in
	black) color=0 ;;
	red) color=1 ;;
	green) color=2 ;;
	yellow) color=3 ;;
	blue) color=4 ;;
	magenta) color=5 ;;
	cyan) color=6 ;;
	white) color=7 ;;
	*) echo "$@" && exit
esac

shift
tput setaf "$color"
echo "$@"
