#!/bin/sh

bold()
{
	tput bold
	echo "$@"
	tput sgr0
}

if [ $# -eq 0 ]; then
	bold "Check out https://github.com/brightio/penelope"
fi

if [ $# -eq 0 ] || echo 'nmap' | grep -iq "$*"; then
	bold 'Nmap'
	echo 'sudo nmap -O -sS -p- "$target"'
	echo 'sudo nmap -sU -p- "$target"'
	echo 'sudo nmap -sC -sV "$target"'
fi

if [ $# -eq 0 ] || echo 'nmap' | grep -iq "$*"; then
	bold 'Sudo'
	echo 'sudo -l'
fi

if [ $# -eq 0 ] || echo 'dirb' | grep -iq "$*"; then
	bold 'Dirb'
	echo 'dirb "http://$target" -r -z 10'
fi

if [ $# -eq 0 ] || echo 'smb' | grep -iq "$*"; then
	bold 'SMB'
	echo 'sudo nbtscan -r "$target"'
	echo 'nmap -v -p 139,445 --script=smb-vuln-ms08-067 --script-args=unsafe=1 "$target"'
fi

