#!/usr/bin/env python3

import sys
import os
import tempfile
import re


def ccat(f):
    os.system(f"ccat {f}")


commands = os.environ["HOME"] + "/.bin/commands.md"

if len(sys.argv) == 1:
    ccat(commands)
    sys.exit(0)

sections = []

with open(commands, "r") as f:
    for line in f:
        if line.startswith("# "):
            sections.append((line[1:].strip(), []))
        sections[-1][1].append(line)

with tempfile.NamedTemporaryFile(mode="w", suffix=".md") as f:
    for arg in sys.argv[1:]:
        for topic, lines in sections:
            if re.search(arg.lower(), topic.lower()):
                f.write("".join(lines))
    f.flush()
    ccat(f.name)
