#!/usr/bin/env python3

from subprocess import check_output as run
import requests
import sys
import time
import os

URL = "https://domains.google.com"
HOSTNAME = "home.christopherdean.org"
USERNAME = os.environ["DDNS_USERNAME"]
PASSWORD = os.environ["DDNS_PASSWORD"]

def check_instances():
    return bool(run(r'ps aux | grep "python3.*\<[d]dns\>"', shell=True))


def get_ip():
    cmds = ["dig +short myip.opendns.com @resolver1.opendns.com", "curl ifconfig.me"]
    for cmd in cmds:
        ip = run(cmd, shell=True).decode("utf-8").strip()
        if ip:
            return ip
    raise Exception("could not determine external ip")


def update_record(ip, url, hostname, username, password):
    url = f"{url}/nic/update?system=dyndns&hostname={hostname}&myip={ip}"
    return requests.get(url, auth=(username, password))

if "-c" in sys.argv and check_instances():
    exit(0)

ip = get_ip()
r = update_record(ip, URL, HOSTNAME, USERNAME, PASSWORD)
if "-q" not in sys.argv:
    print(r.text)

if "-d" in sys.argv:
    while 1:
        time.sleep(5 * 60)
        new_ip = get_ip()
        if new_ip and new_ip != ip:
            ip = new_ip
            update_record(ip, URL, HOSTNAME, USERNAME, PASSWORD)
