#!/bin/sh

sinks="$(audio list sinks)"
sources="$(audio list sources)"

[ -z "$sources" ] && [ "$#" -eq 0 ] && exec audio

args=$(echo "$sinks" | dmenu -i)

[ -z "$args" ] && exit

echo "$args"
exec audio "$args"
