#!/bin/sh

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/dmenu_run"
history="$cachedir/dmenu_history"

selection=$( (tac "$history"; dmenu_path) | awk '!a[$0]++' | dmenu "$@")

if [ -n "$selection" ]; then
	echo "$selection" >> "$history"
	echo "$selection" | ${SHELL:-"/bin/sh"} &
fi

tac "$history" | awk '!a[$0]++' | tac | sponge "$history"
