#!/bin/bash

spawn()
{
	tput bold
	echo "$@"
	tput sgr0
	"$@"
}

base=$(find ~ -name Dotfiles -type d | head -n 1)
if [ -z "$base" ]; then
	echo "please clone the dotfiles repo into a directory called Dotfiles" >&2
	exit 1
fi

: ${1?"Usage: dots save|deploy (--force)"}

cd "$base"
if [ "$1" = "save" ]; then
	shift
	comment="$*${*:+' -- '}$(git diff --name-only | tr '\n' ' ')"
	# spawn git add .
	# spawn git commit -m "$comment"
	# spawn git push
elif [ "$1" = "deploy" ]; then
	if git status 2>/dev/null | grep -q clean; then
		git pull >/dev/null
	elif [ "$2" = "--force" ]; then
		git reset --hard >/dev/null
		git pull >/dev/null
	else
		echo "You have unsaved changes in your dotfiles"
	fi
	./deploy
else
	git "$@"
fi

