#!/bin/bash

[ -d "$HOME/git/Dotfiles/" ] && exec git --git-dir="$HOME/git/Dotfiles/" --work-tree="$HOME" "$@"
[ -d "$HOME/git/dotfiles/" ] && exec git --git-dir="$HOME/git/dotfiles/" --work-tree="$HOME" "$@"
[ -d "$HOME/git/Dotfiles.git/" ] && exec git --git-dir="$HOME/git/Dotfiles.git/" --work-tree="$HOME" "$@"
[ -d "$HOME/git/dotfiles.git/" ] && exec git --git-dir="$HOME/git/dotfiles.git/" --work-tree="$HOME" "$@"
