#!/usr/bin/env python3

import os


def visit(directory, indent=""):
    for f in sorted(os.listdir(directory)):
        path = os.path.join(directory, f)
        if f[0] == '.':
            pass
        elif os.path.isdir(path):
            print(indent + f"[{f}]({path})")
            visit(path, "  " + indent)
        elif os.path.splitext(f)[1] == ".md":
            with open(path, "r") as f:
                title = f.readline().strip().partition(' ')[2]
            print(indent + f"[{title}]({path})")
        else:
            print(indent + f"[{f}]({path})")


visit(".", "- ")
