#!/bin/bash

: ${1?"Usage: latex2pdf filenames"}

while [ $# -gt 0 ]; do
	if ! [ -f $1 ]; then
		shift
		continue
	fi
	filename=${1%.tex}
	pdflatex $1 -interaction errorstopmode #&> /dev/null
	rm -f $filename.aux $filename.log
	shift
done
