#!/usr/bin/env python3

import sys
import re


def colorcat(f):
    colors = {
        "clear": u"\u001b[0;0;0m",
        "pink": u"\u001b[38;5;7m",
        "yellow": u"\u001b[38;5;11m",
        "purple": u"\u001b[38;5;13m",
        "blue": u"\u001b[4m\u001b[38;5;14m",
    }

    subs = {
        r"\[([^\[]*?)\]\((.*)\)": "[{blue}\\1{clear}]({purple}\\2{clear})",
        r"^#(.*)": "{purple}#{pink}\\1",
        r"^(\s*[-+*>])": "{yellow}\\1{clear}",
    }
    for line in f:
        for expr, sub in subs.items():
            line = re.sub(expr, sub, line)
        print(line.format_map(colors), end=colors["clear"])


def main():
    if len(sys.argv) > 1:
        for filename in sys.argv[1:]:
            if filename == "-":
                colorcat(sys.stdin)
            else:
                with open(filename, "r") as f:
                    colorcat(f)
    else:
        colorcat(sys.stdin)


if __name__ == "__main__":
    sys.exit(main())
