#!/usr/bin/env python3

from flask import Flask
from markdown import markdown
import os
app = Flask(__name__)

bg = "#000000"
red = "#CC0000"
green = "#4E9A06"
yellow = "#CBBF3F"
blue = "#3465A4"
magenta = "#a675a1"
cyan = "#06989A"
whitish = "#D3D7CF"
bbg = "#555753"
bred = "#EF2929"
bgreen = "#8AE234"
byellow = "#FCE94F"
bblue = "#729FCF"
bmagenta = "#DCB7DC"
bcyan = "#56c5ea"
bwhitish = "#EEEEEC"

ggreen = "#00ff00"


def header(name):
    return f"""
<html>
<head>
  <title>Notes - {name}</title>
  <link rel="stylesheet" type="text/css" href="/style.css">
  </style>
</head>
<body>
"""


def footer():
    return "</body></html>"


os.chdir("/Users/chridean/.notes")


def reindent(lines):
    newlines = []
    prev_indents = [(0, 0)]
    for line in lines:
        stripped = line.lstrip(" ")
        indent = len(line) - len(stripped)
        if indent > prev_indents[-1][0]:
            prev_indents.append((indent, prev_indents[-1][1] + 4))
        while indent < prev_indents[-1][0]:
            prev_indents.pop()
        indent = prev_indents[-1][1]
        newlines.append(" " * indent + stripped)
    return "\n".join(newlines)


def render(mdfilename):
    with open(mdfilename) as f:
        body = markdown(reindent(f.read().splitlines()))
        return header(mdfilename) + body + footer()


def render_dir(name):
    lines = []
    lines.append(f"# Directory listing for {name}/.\n")
    for f in os.listdir(name):
        lines.append(f"- [{f}]()")
    return header(name) + markdown("\n".join(lines))


@app.route('/')
def index():
    return render('index.md')


@app.route('/style.css')
def style():
    return f"""
body {{
  background: {bg};
  color: {ggreen};
}}
a {{
  color: {bcyan};
}}
h1 {{
    color: {bmagenta};
}}
h2 {{
    color: {bmagenta};
}}
h3 {{
    color: {bmagenta};
}}
h4 {{
    color: {bmagenta};
}}
h1::before {{
    color: {magenta};
    content: "# ";
}}
h2::before {{
    color: {magenta};
    content: "## ";
}}
h3::before {{
    color: {magenta};
    content: "### ";
}}
h4::before {{
    color: {magenta};
    content: "#### ";
}}
ul {{
  list-style: none; /* Remove default bullets */
}}
ul li::before {{
  content: "-";
  color: {yellow}; /* Change the color */
  display: inline-block;
  width: 1em; /* Also needed for space (tweak if needed) */
}}
"""


@app.route('/favicon.ico')
def favicon():
    return ("", 404)


@app.route('/<path:name>')
def markdownfile(name):
    name = name.replace(">", "").replace("<", "")
    if os.path.isdir(name):
        return render_dir(name)
    return render(name)


if __name__ == "__main__":
    app.run()
