#!/bin/sh

# Gives a dmenu prompt to mount unmounted drives and Android phones. If
# they're in /etc/fstab, they'll be mounted automatically. Otherwise, you'll
# be prompted to give a mountpoint from already existsing directories. If you
# input a novel directory, it will prompt you to create that directory.

MOUNT_POINT="$HOME/MOUNT_DIR"

if [ "$1" = "-u" ]; then
	sudo umount "$MOUNT_POINT" && rmdir "$MOUNT_POINT"
	exit $?
fi

usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | grep -v "nvme0n1" | awk '$4==""{printf "%s (%s)\n",$1,$3}')"
if [ "$(echo "$usbdrives" | wc -l)" -eq 1 ]; then
	chosen="$(echo "$usbdrives" | awk '{print $1}')"
else
	chosen="$(echo "$usbdrives" | dmenu -i -p "Mount which drive?")" || exit 1
	chosen="$(echo "$chosen" | awk '{print $1}')"
fi

mkdir -p "$MOUNT_POINT"
partitiontype="$(lsblk -no "fstype" "$chosen")"
case "$partitiontype" in
	"vfat") sudo -A mount -t vfat "$chosen" "$MOUNT_POINT" -o rw,umask=0000;;
	*) sudo -A mount "$chosen" "$MOUNT_POINT"; user="$(whoami)"; ug="$(groups | awk '{print $1}')"; sudo -A chown "$user":"$ug" "$MOUNT_POINT";;
esac
if [ $? -ne 0 ]; then
	notify-send "💻 Failed USB mounting" "$chosen failed to mount to $MOUNT_POINT."
fi

