#!/bin/bash

NOTES="$HOME/notes.md"
NOTES_DIR="$HOME/.notes"

mkdir -p "$NOTES_DIR"
if [ -t 0 ] && [ "$#" -eq 0 ]; then
	if [ -r "$NOTES" ]; then
		exec tmux-pane vim -o "$NOTES" "$NOTES_DIR" -c "call Notes()"
	else 
		exec tmux-pane vim "$NOTES_DIR" -c "call Notes()"
	fi
else 
	exec cat >> "$NOTES"
fi
