#!/bin/bash

exe() { [ -x "$(command -v "$1")" ]; }

! exe xdg-open && exec /usr/bin/open "$@"


if exe xdo; then 
	id=$(xdo id)
	xdo hide "$id"
	xdo hide "$id"
	xdo hide "$id"
	xdo hide "$id"
fi

while [ $# -gt 0 ]; do
	if exe xdo; then
		xdg-open "$1"
	else
		xdg-open "$1" >/dev/null 2>&1
	fi
	shift
done 

if exe xdo; then 
	xdo show "$id"
	xdo show "$id"
	xdo show "$id"
	xdo show "$id"
fi
