#!/bin/bash

exe() { [ -x "$(command -v "$1")" ]; }

! exe xdg-open && exec /usr/bin/open "$@"

do_open() {
	while [ $# -gt 0 ]; do
		xdg-open "$1"
		shift
	done 
}


files=()
swallow=1

while [ $# -gt 0 ]; do
	case $1 in
		-ns | --no-swallow)
			swallow=0
			;;
		*)
			files+=($1)
			;;
	esac
	shift
done


if exe xdotool && [ "$swallow" = 1 ]; then 
	id=$(xdotool getactivewindow)
	xdotool windowunmap "$id"
	do_open "${files[@]}"
	xdotool windowmap "$id"
else
	do_open "${files[@]}"
fi


