#!/usr/bin/env python3

import sys
import os
from pdfrw import PdfReader
from glob import glob
from sh import pdfhead


def title(t):
    if t and t.startswith("(") and t.endswith(")"):
        t = t[1:-1]
    return t


def filename(string):
    return string.strip().replace(" ", "_") + ".pdf"


def main(argv):
    move = False
    while argv and argv[0] in ("-m", "-i"):
        if argv[0] == "-m":
            move = True
        argv = argv[1:]

    files = argv or glob("*.pdf")
    pdfs = {fn: PdfReader(fn) for fn in files}

    for fn, pdf in pdfs.items():
        paper_title = None
        if pdf.Info.Title:
            paper_title = title(pdf.Info.Title)
        if not paper_title:
            paper_title = pdfhead(fn, n=1)
        if paper_title:
            new_fn = filename(paper_title)
            if fn != new_fn:
                print(fn, "-->", new_fn)
                if move:
                    os.rename(fn, new_fn)


if __name__ == "__main__":
    main(sys.argv[1:])
