#!/usr/bin/env python3

import sys
import os
from pdfrw import PdfReader
from glob import glob


def title(t):
    if t and t.startswith("(") and t.endswith(")"):
        t = t[1:-1]
    return t


def filename(string):
    return string.replace(" ", "_") + ".pdf"


def main(argv):
    move = False
    interactive = False
    while argv and argv[0] in ("-m", "-i"):
        if argv[0] == "-m":
            move = True
        if argv[0] == "-i":
            interactive = True
        argv = argv[1:]

    files = argv or glob("*.pdf")
    pdfs = {fn: PdfReader(fn) for fn in files}

    for fn, pdf in pdfs.items():
        paper_title = None
        if pdf.Info.Title:
            paper_title = title(pdf.Info.Title)
        if interactive:
            print(pdf.Info)
            page = pdf.pages[0]
            print(page.extractText)
            paper_title = input("title: ")
        if paper_title:
            new_fn = filename(paper_title)
            print(fn, "-->", new_fn)
            if move:
                os.rename(fn, new_fn)


if __name__ == "__main__":
    main(sys.argv[1:])
