#!/usr/bin/env python3

import sys
import os
from pdfrw import PdfReader
from glob import glob


def title(fn):
    t = PdfReader(fn).Info.Title
    if t and t.startswith("(") and t.endswith(")"):
        t = t[1:-1]
    return t

def filename(string):
    return string.replace(" ", "_") + ".pdf"

def main(argv):
    move = False
    if argv and argv[0] == "-m":
        move = True
        argv = argv[1:]

    files = argv or glob("*.pdf")
    titles = ((f, title(f)) for f in files if title(f))

    for f, t in titles:
        print(f, "-->", t)
        if move:
            os.rename(f, filename(t))


if __name__ == "__main__":
    main(sys.argv[1:])
