#!/bin/sh

if timeout 5 ping -c 1 172.27.144.107 >/dev/null 2>&1; then
	exec print-bb "$@"
fi

if [ $1 = "-2" ]; then
	lp -o number-up=2 -o sides=two-sided-short-edge "$@"
else
	lp -o sides=two-sided-long-edge "$@"
fi 
