#!/bin/sh

print_bb()
{
	server="172.27.144.107"

	while [ $# -gt 0 ]; do
		cat "$1" | netcat -w 1 "$server" 9100
		shift
	done
}

print_mk()
{
	server="$1"
	shift


	while [ $# -gt 0 ]; do
		cat "$1" | netcat -w 1 "$server.eecs.utk.edu" 9100
		shift
	done
}

print_home()
{
	email onn5826urn47@hpeprint.com -a "$@" -s "Paper" -m "/dev/null"
}

# if ping -c 1 -w 1 172.27.144.107 >/dev/null 2>&1; then
	# exec print-bb "$@"
# fi

print_home "$@"
exit $?

if [ "$1" = "-2" ]; then
	lp -o number-up=2 -o sides=two-sided-short-edge "$@"
else
	lp -o sides=two-sided-long-edge "$@"
fi 
