#!/bin/sh
#
# rotate_desktop.sh
#
# Rotates modern Linux desktop screen and input devices to match. Handy for
# convertible notebooks. Call this script from panel launchers, keyboard
# shortcuts, or touch gesture bindings (xSwipe, touchegg, etc.).
#
# Using transformation matrix bits taken from:
#   https://wiki.ubuntu.com/X/InputCoordinateTransformation
#

# Configure these to match your hardware (names taken from `xinput` output).
TOUCHPAD='SYNA2393:00 06CB:7A13 Touchpad'
TOUCHSCREEN='Wacom HID 488F Finger touch'

if [ -z "$1" ] || ! echo "$1" | grep -E "^normal$|^inverted$|^left$|^right$"; then
	echo "Missing orientation."
	echo "Usage: $0 [normal|inverted|left|right] [revert_seconds]"
	echo
	exit 1
fi

do_rotate()
{
	xrandr --output $1 --rotate $2

	TRANSFORM='Coordinate Transformation Matrix'
	normal="1 0 0 0 1 0 0 0 1"
	inverted="-1 0 1 0 -1 1 0 0 1"
	left="0 -1 1 1 0 0 0 0 1"
	right="0 1 0 -1 0 1 0 0 1"

	eval "choice=\$$2"

	xinput set-prop "$TOUCHPAD"    "$TRANSFORM" $choice
	xinput set-prop "$TOUCHSCREEN" "$TRANSFORM" $choice
}

XDISPLAY=`active-monitor`
XROT=`xrandr --current --verbose | grep -F "$XDISPLAY" | egrep -o ' (normal|left|inverted|right) '`

do_rotate $XDISPLAY $1

if [ ! -z "$2" ]; then
	sleep $2
	do_rotate $XDISPLAY $XROT
	exit 0
fi

