#!/bin/bash

set -e

id=$(xdotool getactivewindow)
xdotool windowunmap "$id"
xdotool windowunmap "$id"
xdotool windowunmap "$id"
"$@"
xdotool windowmap "$id"
xdotool windowmap "$id"
xdotool windowmap "$id"
