#!/usr/bin/env python3
import sys

"""
Prints out file as a table
"""


def common_indent(lines):
    if len(lines) == 0:
        return ""
    common_indent = lines[0]

    for line in lines[1:]:
        while not line.startswith(common_indent):
            common_indent = common_indent[:-1]

    return common_indent


def tablign(string, seperator=" "):
    lines = string.splitlines()
    indent = common_indent(lines)
    lines = [line[len(indent):].split(seperator) for line in lines]
    sizes = [0] * max(len(line) for line in lines)

    for line in lines:
        for i, field in enumerate(line):
            sizes[i] = max(sizes[i], len(field))

    lines = [seperator.join(s.ljust(l)
                            for s, l in zip(line, sizes)) for line in lines]

    return indent + ("\n" + indent).join(lines)


def usage():
    print("Usage: tablign [-s align-on] [file]", file=sys.stderr)
    sys.exit(1)


def main():
    sep = " "
    if len(sys.argv) in (1, 3):
        s = sys.stdin.read()
    elif len(sys.argv) in (2, 4):
        with open(sys.argv[-1], "r") as f:
            s = f.read()
    if len(sys.argv) in (3, 4):
        if sys.argv[1] != "-s":
            usage()
        sep = sys.argv[2]

    print(tablign(s, sep))
    return 0


if __name__ == "__main__":
    sys.exit(main())
