#!/bin/sh
#
# Write/remove a task to do later.
#
# Select an existing entry to remove it from the file, or type a new entry to
# add it.
#

dir="$(find ~/git -type d -name personal_notes)"
[ -n "$dir" ] || (echo "Could not find notes directory" && exit 1)
cd "$dir"
git pull
file="todo"
touch "$file"
height=$(wc -l "$file")
prompt="Add/delete a task: "

cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file")
while [ -n "$cmd" ]; do
 	if grep -q "^$cmd\$" "$file"; then
		grep -v "^$cmd\$" "$file" > "$file.$$"
		mv "$file.$$" "$file"
 	else
		echo "$cmd" >> "$file"
 	fi

	height=$(wc -l "$file")
	cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file")
done

git add todo
git commit -m "personal notes update"
git remote -v | grep -q "push" && git push

exit 0
