#!/bin/sh

touchpad=$(xinput | grep TouchPad | sed "s/.*=\([0-9]*\).*/\1/")

xinput list-props $touchpad | grep "Device Enabled" | awk '{ print 1-$NF }' | xargs xinput set-prop $touchpad "Device Enabled"

