#!/bin/sh

BOLD="$(tput bold)"
CLEAR="$(tput sgr0)"

spawn()
{
	test -t 1 && echo "${BOLD}$@${CLEAR}"
	"$@"
}


if [ $# -eq 2 ]; then
	spawn nmcli device wifi connect "$1" password "$2"
elif [ $# -eq 1 ]; then
	case "$1" in 
		list) spawn nmcli device wifi ;;
		off) spawn nmcli radio wifi off ;;
		on) spawn nmcli radio wifi on ;;
		restart)
			spawn nmcli radio wifi off
			spawn nmcli radio wifi on
			;;
		recon*) nmcli --terse con show --active | cut -d: -f 1 | xargs nmcli con up ;;
		*) spawn nmcli device wifi connect "$1" ;;
	esac
else
	echo "Usage: wifi network_SSID [network_password]"
	spawn nmcli device wifi
fi
