#!/bin/sh

spawn()
{
	tput bold
	echo "$@"
	tput sgr0
	"$@"
}


if [ $# -eq 2 ]; then
	spawn nmcli device wifi connect "$1" password "$2"
elif [ $# -eq 1 ]; then
	if [ "$1" = "list" ]; then
		spawn nmcli device wifi
	elif [ "$1" = "off" ]; then
		spawn nmcli radio wifi off
	elif [ "$1" = "on" ]; then
		spawn nmcli radio wifi on
	elif [ "$1" = "restart" ]; then
		spawn nmcli radio wifi off
		spawn nmcli radio wifi on
	else
		spawn nmcli device wifi connect "$1"
	fi
else
	echo "Usage: wifi network_SSID [network_password]"
	spawn nmcli device wifi
fi
