#!/bin/bash
-()
{
	builtin cd -
}
export -f -

j()
{
	jmps="$HOME/.jmp/to.txt"
	if [ $# -ne 0 ]
	then
		pattern=".*$(echo "$@" | sed "s/\s\+/.*\/.*/g")[^\/]*$"
	fi

	if [ -z $(echo $PWD | grep "$pattern") ]
	then
		new_dir=$(
		tac $jmps |
		grep -v "^$PWD$" |
		grep "$pattern" |
		awk '{ if (!a[$0]++) print $0 }' |
		head -1
		)
	else
		new_dir=$(
		tac $jmps |
		grep "$pattern" |
		awk '{ if (!a[$0]++) print $0 }' |
		awk '{ print $0; if(!a) a = $0 }; END { print a }' |
		grep -m 1 -A 1 "^$PWD$" |
		tail -1
		)

	fi

	if ! [ -z "$new_dir" ]
	then 
		if [ -d "$new_dir" ]
		then
			builtin cd $new_dir 
		else
			temp=$(mktemp)
			mv $jmps $temp
			grep -v "$new_dir" $temp > $jmps
			rm $temp
			j
		fi
	fi
}

export -f j

jsetup()
{
	mkdir -p $HOME/.jmp
	find $HOME -type d -not -path "*/\.*" > $HOME/.jmp/to.txt
}
