#!/bin/bash
-()
{
	builtin cd -
}
export -f -

j()
{
	if [ $# -eq 0 ]; then
		builtin cd ~ && ls
		return
	fi

	OLD_JUMP=$JUMP
	JUMP=$1

	if [ "$JUMP"="$OLD_JUMP" ] && [[ $PWD == *$JUMP ]] 
	then
		builtin cd `find ~ -type d -name "*$1" 2> /dev/null | grep -v "\/\." | tee /dev/stdout | grep -A 1 -m 1 "$PWD" | tail -1` && pwd | sed "s|$HOME|~|g" && ls
	else
		builtin cd `find ~ -type d -name "*$1" 2> /dev/null | grep -v "\/\." | grep "$1$" | grep -v "^$PWD$" | head -1` && pwd | sed "s|$HOME|~|g" && ls
	fi
}

export -f j

jj()
{
	if [ $# -eq 0 ]; then
		builtin cd ~ && ls
		return
	fi

	OLD_JUMP=$JUMP
	JUMP=$1

	if [ "$JUMP"="$OLD_JUMP" ] && [[ $PWD == *$JUMP ]] 
	then
		builtin cd `find . -type d -name "*$1" 2> /dev/null | grep -v "\/\." | tee /dev/stdout | grep -A 1 -m 1 "$PWD" | tail -1` && pwd | sed "s|$HOME|~|g" && ls
	else
		builtin cd `find . -type d -name "*$1" 2> /dev/null | grep -v "\/\." | grep "$1$" | grep -v "^$PWD$" | head -1` && pwd | sed "s|$HOME|~|g" && ls
	fi
}

export -f jj

aj()
{
	jmps="$HOME/.jmp/to.txt"
	if [ $# -ne 0 ]
	then
		pattern=".*$(echo "$@" | sed "s/\s\+/.*\/.*/g")[^\/]*$"
	fi

	if [ -z $(echo $PWD | grep "$pattern") ]
	then
		new_dir=$(
			tac $jmps |
			grep -v "^$PWD$" |
			grep "$pattern" |
			awk '{ if (!a[$0]++) print $0 }' |
			head -1
		)
	else
		new_dir=$(
			tac $jmps |
			grep "$pattern" |
			awk '{ if (!a[$0]++) print $0 }' |
			awk '{ print $0; if(!a) a = $0 }; END { print a }' |
			grep -m 1 -A 1 "^$PWD$" |
			tail -1
		)
		
	fi

	if ! [ -z "$new_dir" ]
	then 
		builtin cd $new_dir
	fi
}

export -f aj
