alias c="clear"

alias bashrc=". ~/.bashrc"

alias python="python3"

alias xcut="xclip -sel clip"
alias xpaste="xclip -o -sel clip"

alias open="xdg-open"

alias make="make -j\$(nproc)"

alias tail="tail -n \$(echo \$(tput lines)-2|bc)"
alias tail="tail -n \$(echo \$(tput lines)-2|bc)"


alias cd..="cd .."
alias ..="cd .."
